name: "CI"

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  ci:
    name: "Build, Lint and Test"
    runs-on: ubuntu-latest

    steps:
      - name: "Check out protocol-plugins"
        uses: actions/checkout@v4

      - name: "Install Pnpm"
        uses: pnpm/action-setup@v4

      - name: "Setup Node.js"
        uses: actions/setup-node@v4
        with:
          cache: pnpm
          node-version: "22.22.3"

      - name: "Install dependencies"
        run: pnpm install --frozen-lockfile

      - name: "Build"
        run: pnpm build

      - name: "Lint"
        run: pnpm lint

      - name: "Run tests with coverage"
        run: pnpm coverage

      - name: "Upload coverage to Codecov"
        uses: codecov/codecov-action@v4
        with:
          files: ./coverage/lcov.info
          token: ${{ secrets.CODECOV_TOKEN }}
          fail_ci_if_error: false
